"""Merge JSON seeds (+ vectors) into db/seeds/seed.sql for Neon.
Run: python scripts/build_seed_sql.py   (after build_vectors.py)
"""
import json


def q(s):
    return "'" + str(s).replace("'", "''") + "'"


schemes = json.load(open("db/seeds/schemes.json", encoding="utf-8"))
sources = json.load(open("db/seeds/sources.json", encoding="utf-8"))
facts = json.load(open("db/seeds/facts.json", encoding="utf-8"))
vecs = {e["id"]: e["vec"] for e in json.load(open("db/seeds/vectors.json", encoding="utf-8"))["faqs"]}
try:
    directory = json.load(open("db/seeds/fund_directory.json", encoding="utf-8"))
except FileNotFoundError:
    directory = []

lines = ["-- Generated by scripts/build_seed_sql.py. Do not hand-edit.",
         "BEGIN;"]
for s in schemes:
    lines.append(
        f"INSERT INTO schemes (id, name, category, amc, scheme_page_url) VALUES "
        f"({q(s['id'])}, {q(s['name'])}, {q(s['category'])}, {q(s['amc'])}, {q(s['scheme_page_url'])}) "
        f"ON CONFLICT (id) DO NOTHING;")
for s in sources:
    sid = q(s["scheme_id"]) if s["scheme_id"] else "NULL"
    lines.append(
        f"INSERT INTO sources (url, title, kind, scheme_id, last_verified_at, fetch_status) VALUES "
        f"({q(s['url'])}, {q(s['title'])}, {q(s['kind'])}, {sid}, CURRENT_DATE, 'verified') "
        f"ON CONFLICT (url) DO NOTHING;")
for f in facts:
    vec = "[" + ",".join(f"{x:.5f}" for x in vecs[f["id"]]) + "]"
    pop = "TRUE" if f["is_popular"] else "FALSE"
    sid = q(f["scheme_id"]) if f["scheme_id"] else "NULL"
    lines.append(
        f"INSERT INTO facts (id, scheme_id, topic, question, answer, source_id, verified_at, is_popular, embedding) "
        f"SELECT {q(f['id'])}, {sid}, {q(f['topic'])}, {q(f['question'])}, {q(f['answer'])}, "
        f"sources.id, {q(f['verified_at'])}, {pop}, '{vec}'::vector "
        f"FROM sources WHERE sources.url = {q(f['source_url'])} "
        f"ON CONFLICT (id) DO NOTHING;")
for d in directory:
    lines.append(
        f"INSERT INTO fund_directory (fund_name, url) VALUES ({q(d['fund_name'])}, {q(d['url'])}) "
        f"ON CONFLICT (url) DO NOTHING;")
lines.append("COMMIT;")

with open("db/seeds/seed.sql", "w", encoding="utf-8") as fh:
    fh.write("\n".join(lines) + "\n")
print(f"WROTE db/seeds/seed.sql schemes={len(schemes)} sources={len(sources)} facts={len(facts)} directory={len(directory)}")
